project:
  type: website

website:
  title: "Justin Dyck"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: portfolio.qmd
        text: Portfolio
      - href: CV.qmd
        text: Curriculum Vitae
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



