project:
  type: website

website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: ABOUTTT

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



